<?php
/*
 * sidemenu example
 *
 * @package     Application
 * @author      Vallo Reima
 * @copyright   (C)2012
 */
$icon = "$ats/vallo-reima.ico'";
$foot = "$title © " . date('Y');
$foot .= ' <a href="mailto:info@vallo.me?subject=' . $title . '">vallo.me</a>';
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="author" content="Vallo Reima">
    <title><?php echo $title; ?></title>
    <link rel="shortcut icon" href="<?php echo $icon; ?>" type="image/x-icon">
    <link href="example.css" rel="stylesheet" type="text/css">
    <script src="common.js" type="text/javascript"></script>
    <script src="sidemenu.js" type="text/javascript"></script>
    <script type="text/javascript">

      var mnu;  /* menu object */

      window.onload = function() {
        mnu = new SideMenu(); /* activate menu */
      };

      function Finish() {
        /*  example's exit  */
        mnu.Term();
        var tnk = '<?php echo "$title: $txt->tnk!"; ?>';
        document.body.innerHTML = '<h3>&nbsp;' + tnk + '</h3>';
      }

    </script>
  </head>
  <body>
    <div id="head" class="head">
      <span><?php echo $txt->hdg; ?></span>
      <button type="button" onClick="Finish();"><?php echo $txt->end; ?></button>
    </div>
    <div class="areaRight">	
      <div class="areaLeft">	
        <div id="menu" class="menu">
          <?php echo $mnu->Menu($ops); ?>
        </div>
        <div class="contents">
          <div class="section" id="section">
            <?php echo $txt->fts; ?>
          </div>
          <div id="content" class="content">
            <?php echo $txt->ins; ?>
            <noscript><br /><?php echo $txt->jsd; ?></noscript>
          </div>
        </div>
      </div>
    </div>
    <div id="foot" class="foot">
      <?php echo $foot; ?>
    </div>
  </body>
</html>
