BEGIN TRANSACTION;
DROP TABLE IF EXISTS "texts";
CREATE TABLE "texts" ("type" char(3) DEFAULT (NULL) ,"code" varchar(10) NOT NULL ,"en" varchar(40) NOT NULL ,"et" varchar(40) DEFAULT (NULL) ,"ru" varchar(40) DEFAULT (NULL) );
INSERT INTO "texts" VALUES('sct','abt','About','Teave','Насчёт');
INSERT INTO "texts" VALUES('sct','aty','Activity','Tegevus','Активность');
INSERT INTO "texts" VALUES('sct','clm','Calendars','Kalendrid','Календари');
INSERT INTO "texts" VALUES('sct','cls','Clients','Kliendid','Клиенты');
INSERT INTO "texts" VALUES('sct','crs','Countries','Riigid','Государства');
INSERT INTO "texts" VALUES('sct','hme','Home','Avaleht','Начало');
INSERT INTO "texts" VALUES('sct','myd','My data','Minu andmed','Мои данные');
INSERT INTO "texts" VALUES('sct','myr','My times','Minu ajad','Мои времена');
INSERT INTO "texts" VALUES('sct','nck','Nickname','Nimetus','Название');
INSERT INTO "texts" VALUES('sct','nms','Names','Nimetused','Названия');
INSERT INTO "texts" VALUES('sct','nws','News','Uudised','Новости');
INSERT INTO "texts" VALUES('sct','pfs','Preferences','Eelistused','Предпочтения');
INSERT INTO "texts" VALUES('sct','prs','Persons','Isikud','Лица');
INSERT INTO "texts" VALUES('sct','pts','Posts','Ametid','Должности');
INSERT INTO "texts" VALUES('sct','rgn','Registering','Registreerimine','Регистрация');
INSERT INTO "texts" VALUES('sct','rpt','Reports','Aruanded','Отчёты');
INSERT INTO "texts" VALUES('sct','sdl','Schedule','Ajakava','Расписание');
INSERT INTO "texts" VALUES('sct','sct','Sections','Jaotised','Секции');
INSERT INTO "texts" VALUES('sct','skd','Schedules','Ajakavad','Расписания');
INSERT INTO "texts" VALUES('sct','set','Settings','Seaded','Установки');
INSERT INTO "texts" VALUES('sct','stf','Staff','Töötajad','Персонал');
INSERT INTO "texts" VALUES('sct','sts','Statuses','Olekud','Статусы');
INSERT INTO "texts" VALUES('sct','sys','System','Süsteem','Система');
INSERT INTO "texts" VALUES('sct','tps','Types','Tüübid','Типы');
INSERT INTO "texts" VALUES('sct','urs','Users','Kasutajad','Пользователи');
INSERT INTO "texts" VALUES('sct','uts','Units','Üksused','Подразделения');
INSERT INTO "texts" VALUES('sct','lgc','Language','Keel','Язык');
INSERT INTO "texts" VALUES('sct','tst','Test','Test','Test');
INSERT INTO "texts" VALUES('sct','log','Log','Päevik','Журнал');
INSERT INTO "texts" VALUES('sct','imp','Import','Import','Импорт');
INSERT INTO "texts" VALUES('sct','tpn','Timeplan','Ajaplaan','План времени');
INSERT INTO "texts" VALUES('sct','rvd','Registrations','Registreeringud','Регистрации');
INSERT INTO "texts" VALUES('sct','nsw','News','Uudised','Новости');
INSERT INTO "texts" VALUES('sct','rsv','Reservation','Reserveerimine','Резервирование');
INSERT INTO "texts" VALUES('sct','bkd','Bookings','Broneeringud','Бронировании');
INSERT INTO "texts" VALUES('sct','ovt','Oversight','Järelevalve','Присмотр');
INSERT INTO "texts" VALUES('sct','sms','Sending SMS','SMS saatmine','Отправка SMS');
INSERT INTO "texts" VALUES('sct','smt','Sent SMS','Saadetud SMS','Отправлено SMS');
INSERT INTO "texts" VALUES('sct','smp','SMS providers','SMS pakkujad','SMS поставщики');
INSERT INTO "texts" VALUES('sct','cus','Currencies','Valuutad','Валюты');
INSERT INTO "texts" VALUES('sct','adm','Administering','Administreerimine','Администрация');
INSERT INTO "texts" VALUES('sct','ovs','Oversights','Järelevalved','Присмотры');
INSERT INTO "texts" VALUES('sct','cur','Currency','Valuuta','Валюта');
INSERT INTO "texts" VALUES('sct','ity','Identity','Identiteet','Идентичность');
INSERT INTO "texts" VALUES('sct','kns','Kinds','Liigid','Виды');
INSERT INTO "texts" VALUES('sct','frs','Friends','Sõbrad','Друзья');
INSERT INTO "texts" VALUES('sct','sns','Sendings','Saatmised','Отправления');
INSERT INTO "texts" VALUES('sct','mtn','Maintenance','Haldamine','Поддержание');
INSERT INTO "texts" VALUES('sct','ggl','Google credentials','Google volitused','Google полномочия');
INSERT INTO "texts" VALUES(NULL,'end','Finish','Lõpeta','Заверши');
INSERT INTO "texts" VALUES(NULL,'tnk','Thank You for attention','Täname Teid tähelepanu eest','Благодарим Вас за внимаание');
INSERT INTO "texts" VALUES(NULL,'hdg','Side menu generator and handler','Külgmenüü generaator ja käitleja','Генератор и обработчик бокового меню');
INSERT INTO "texts" VALUES(NULL,'fts','Configurable multilingual hierarchical menus','Seadistatavad mitmekeelsed hierarhilised menüüd','Настраиваемые многоязычные иерархические меню');
INSERT INTO "texts" VALUES(NULL,'ins','Select the items in the menu on the left...','Valige vasakult menüüjaotisi...','Выберите разделы меню слева...');
INSERT INTO "texts" VALUES(NULL,'jsd','JavaScript is disabled. Please enable and reload the page','JavaScript on välja lülitatud. Palun lülitage sisse ja laadige lehekülg uuesti','JavaScript отключен. Пожалуйста, включите и перезагрузите страницу');
INSERT INTO "texts" VALUES(NULL,'ecfg','Couldn''t load the configuration','Ei saanud laadida konfiguratsiooni','Не удалось загрузить конфигурацию');
COMMIT;
